---
version: 2.6

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go test ./...

builds:
  - main: ./cmd/brig
    id: "brig"
    binary: brig
    ldflags:
      - -extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm64

upx:
  - enabled: true
    goos: [darwin, linux]
    compress: best

  - enabled: false
    goos: [freebsd]

  - enabled: true
    goos: [windows]
    goarch: [amd64]
    compress: best

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.xz
    format_overrides:
      - goos: windows
        formats:
          - zip
    wrap_in_directory: false
    files:
      - LICENSE
      - docs/_README.md
      - brigrc

homebrew_casks:
  - name: brig
    description: "the lightweight, native Go CLI for devcontainers"
    repository:
      owner: nlsantos
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: nlsantos
      email: nlsantos@users.noreply.github.com
    directory: Casks
    url:
      verified: "github.com/nlsantos/brig"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xatttr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brig"]
          end

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
