version: 2.6

before:
    hooks:
        - go mod tidy
        - go test ./...

builds:
    - main: ./cmd/brig
      id: "brig"
      binary: brig
      ldflags:
        - -extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
      env:
        - CGO_ENABLED=0
      goos:
        - linux
        - darwin
        - windows
      goarch:
        - amd64
        - arm64

upx:
  - enabled: true
    goos: [linux, darwin]
    compress: best

  - enabled: true
    goos: [windows]
    goarch: [amd64]
    compress: best

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.xz
    format_overrides:
      - goos: windows
        formats:
          - zip
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - brigrc

brews:
  - name: nlsantos
    repository:
      owner: nlsantos
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: nlsantos
      email: nlsantos@users.noreply.github.com
    homepage: https://github.com/nlsantos/brig
    description: "brig: the lightweight, native Go CLI for devcontainers"
    test: system "#{bin}/brig --version"
    install: bin.install "brig"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
