FLAVOR_SUGGESTIONS: false
APPLY_FIXES: all
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - SPELL_CSPELL
  - SPELL_LYCHEE
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: "\/testdata\/"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "docs/index.md"
