FLAVOR_SUGGESTIONS: false
APPLY_FIXES: all
DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
  - SPELL_LYCHEE
